services:

  # Общие настройки Kafka для переиспользования в каждом брокере
  x-kafka-common:
    &kafka-common
    image: bitnamilegacy/kafka:3.7
    environment:
      &kafka-common-env
      KAFKA_ENABLE_KRAFT: yes                          # Включение режима KRaft (Kafka без Zookeeper)
      ALLOW_PLAINTEXT_LISTENER: yes                    # Разрешение незашифрованных подключений
      KAFKA_KRAFT_CLUSTER_ID: practicum                # Уникальный идентификатор KRaft-кластера (задан один раз при первом запуске)
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT"  # Протоколы для разных типов слушателей
      KAFKA_CFG_PROCESS_ROLES: broker,controller       # Роль узла: одновременно брокер и контроллер метаданных
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER  # Контроллер использует listener CONTROLLER (для внутреннего кворума метаданных)
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093  # Участники кворума контроллеров
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: false       # Отключить автосоздание топиков
    networks:
      - proxynet

  kafka-0:
    <<: *kafka-common
    hostname: kafka-0
    restart: always
    ports:
      - "127.0.0.1:9094:9094"                           # Проброс EXTERNAL порта наружу (доступ извне)
    environment:
      <<: *kafka-common-env
      KAFKA_CFG_NODE_ID: 0                              # Уникальный ID узла внутри кластера
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094  # Список слушателей для разных задач
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-0:9092,EXTERNAL://127.0.0.1:9094  # Адреса, которые Kafka "рекламирует" наружу
    volumes:
      - kafka_0_data:/bitnamilegacy/kafka                     # Хранилище данных Kafka

  kafka-1:
    <<: *kafka-common
    hostname: kafka-1
    restart: always
    ports:
      - "127.0.0.1:9095:9094"                           # Проброс EXTERNAL порта наружу (доступ извне)
    environment:
      <<: *kafka-common-env
      KAFKA_CFG_NODE_ID: 1                              # Уникальный ID узла внутри кластера
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094  # Список слушателей для разных задач
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,EXTERNAL://127.0.0.1:9095  # Адреса, которые Kafka "рекламирует" наружу
    volumes:
      - kafka_1_data:/bitnamilegacy/kafka                     # Хранилище данных Kafka

  kafka-2:
    <<: *kafka-common
    hostname: kafka-2
    restart: always
    ports:
      - "127.0.0.1:9096:9094"
    environment:
      <<: *kafka-common-env
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,EXTERNAL://127.0.0.1:9096
    volumes:
      - kafka_2_data:/bitnamilegacy/kafka

  # Интерфейс управления Kafka (Kafka UI)
  ui:
    image: provectuslabs/kafka-ui:v0.7.0
    restart: always
    ports:
      - "8085:8080"                         # Интерфейс доступен на localhost:8080
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka-0:9092 # Указываем, где искать брокер Kafka
      KAFKA_CLUSTERS_0_NAME: kraft                     # Название кластера в UI
    networks:
      - proxynet

  # Schema Registry
  schema-registry:
    image: bitnamilegacy/schema-registry:7.6
    ports:
      - '127.0.0.1:8081:8081'                           # API для регистрации/получения схем
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
    environment:
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081    # Прослушивание запросов на порту 8081
      SCHEMA_REGISTRY_KAFKA_BROKERS: PLAINTEXT://kafka-0:9092,PLAINTEXT://kafka-1:9092,PLAINTEXT://kafka-2:9092  # Список брокеров Kafka
    networks:
      - proxynet

  # База данных PostgreSQL (источник данных)
  postgres:
    image: debezium/postgres:16
    hostname: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres-user                     # Имя пользователя
      POSTGRES_PASSWORD: postgres-pw                   # Пароль
      POSTGRES_DB: customers
    volumes:
      - ./postgres/custom-config.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf # Название базы данных
    networks:
      - proxynet

  kafka-connect:
    build:
      context: ./kafka-connect
    ports:
      - "8083:8083"  # REST API Kafka Connect
      - "9875:9875"
      - "9876:9876"
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
      - schema-registry
      - postgres
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka-0:9092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: 'kafka-connect'
      CONNECT_REST_ADVERTISED_HOST_NAME: 'localhost'

      # Хранение конфигурации, смещений и статусов
      CONNECT_CONFIG_STORAGE_TOPIC: 'connect-config-storage'
      CONNECT_OFFSET_STORAGE_TOPIC: 'connect-offset-storage'
      CONNECT_STATUS_STORAGE_TOPIC: 'connect-status-storage'
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1

      # Конвертеры
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      # Пути к плагинам
      CONNECT_PLUGIN_PATH: /usr/share/java,/etc/kafka-connect/jars
      # Export JMX metrics to :9876/metrics for Prometheus
      KAFKA_JMX_PORT: '9875'
      KAFKA_OPTS: "-javaagent:/opt/jmx_prometheus_javaagent-0.15.0.jar=9876:/opt/kafka-connect.yml"
      # Read connection password from file
      CONNECT_CONFIG_PROVIDERS: "file"
      CONNECT_CONFIG_PROVIDERS_FILE_CLASS: "org.apache.kafka.common.config.provider.FileConfigProvider"
    volumes:
      - ./confluent-hub-components/:/etc/kafka-connect/jars
    networks:
      - proxynet


  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    links:
      - kafka-connect
    networks:
      - proxynet

  grafana:
    build:
      context: ./grafana
    ports:
      - 3000:3000
    networks:
      - proxynet

networks:
  proxynet:
    name: custom_network                               # Общая пользовательская сеть Docker

volumes:
  kafka_0_data:
  kafka_1_data:
  kafka_2_data: